spring.data.mongodb.uri=mongodb+srv://ksaikumart123:Saikumar@2003@cluster0.8gip9fb.mongodb.net/studentdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=studentdb
sspring.data.mongodb.uri=mongodb://localhost:27017/studentdb
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
